### ISSUE TITLE
iocp and twapi::tls_socket cause hanging system for me

### ISSUE THREAD

**Issue by apnadkarni** [apnadkarni/iocp#15]
Moved from https://sourceforge.net/p/twapi/bugs/191/

Dear Ashok,
thank you for great twapi and iocp.

With the following lines, I get a block wish window (not responding any more) :

package require iocp_inet 
rename ::socket ::socket_ori
rename ::iocp::inet::socket ::socket
package require twapi
package require http
proc ::http::Log {args} {
    puts "\[http\]:$args"
}
http::register https 443 {::twapi::tls_socket}
http::geturl https://www.elmicron.de/labelers.csv

This is TWAPI (developper Version) 4.4.0, http 2.9.1 and wish 8.6.10 (VC6 self compiled), iocp 1.0.0.

I get the following console output (it is tricked, as the console stalls and copy&paste is not possible) (screenshot attached):

(bin) 6 % package require iocp_inet 
1.0.0
(bin) 7 % rename ::socket ::socket_ori
(bin) 8 % rename ::iocp::inet::socket ::socket(bin) 1 % package require twapi
4.4.0
(bin) 2 % package require http
2.9.1
(bin) 3 % proc ::http::Log {args} {
>   puts "\[http\]:$args"
> }
(bin) 4 % http::register https 443 {::twapi::tls_socket}
443 ::twapi::tls_socket
(bin) 5 % http::geturl https://www.elmicron.de/labelers.csv
[http]:^A1 URL https://www.elmicron.de/labelers.csv - token ::http::1
[http]:{Using rc0 for www.elmicron.de:443 - token ::http::1} {}
[http]:^B1 begin sending request - token ::http::1
[http]:^C1 end sending request - token ::http::1
[http]:^D1 begin receiving response - token ::http::1

When I remove the first 3 lines (iocp initialization), it works correctly:

(bin) 1 % package require twapi
4.4.0
(bin) 2 % package require http
2.9.1
(bin) 3 % proc ::http::Log {args} {
>   puts "\[http\]:$args"
> }
(bin) 4 % http::register https 443 {::twapi::tls_socket}
443 ::twapi::tls_socket
(bin) 5 % http::geturl https://www.elmicron.de/labelers.csv
[http]:^A1 URL https://www.elmicron.de/labelers.csv - token ::http::1
[http]:{Using rc0 for www.elmicron.de:443 - token ::http::1} {}
[http]:^B1 begin sending request - token ::http::1
[http]:^C1 end sending request - token ::http::1
[http]:^D1 begin receiving response - token ::http::1
[http]:^E1 end of response headers - token ::http::1
[http]:^F1 end of response body (unchunked) - token ::http::1
[http]:{Closing socket rc0 (no connection info)}
::http::1

I am sorry for this report. Come to me if I may be of any help.
Thank you,
Harald

**Comment by apnadkarni** [comment]
Fixed in 1.0.9.

**Comment by oehhar** [comment]
Hi Ashok,
thank you for looking into this, I appreciate.
I can confirm, that it works correctly in the exact setup now for me.

Thank you,
Harald

P.S.
The test recipe should be 

`puts "\[http\]:$args"

instead 

`puts` "[http]:$args"
